# Document:
# http://simiki.org/docs/configuration.html

url: http://wiki.ferstar.org/
title: My Personal Wiki Site
keywords: wiki, linux, python
description: "ferstar's personal wiki, powered by vim and markdown. Focus on Python, Linux, Ops-Dev etc."
author: ferstar
theme: yasimple

##### Deploy #####
deploy:
  - type: git
    destination: output
    remote: origin
    branch: gh-pages
